### ISSUE TITLE
Independent State of Samoa (ISO 3166-2:WS) missing

### ISSUE THREAD

**Issue by enigma127** [mledoze/countries#278] opened 2018-02-26 19:54 UTC
The Independent State of Samoa is missing in countries.json (UN Member State). See the website of the United Nations or https://en.wikipedia.org/wiki/Member_states_of_the_United_Nations.

Note: American Samoa is not the same as Samoa. The latter is an independent state, the former not.

**Comment by blumk** [comment] 2018-02-27 08:39
I can confirm that ISO 3166-2:WS is missing. 

Looks like the countries.json contains one country that should not be in the list since it already contains 249 countries (see [ISO_3166-1 Current_codes](https://en.wikipedia.org/wiki/ISO_3166-1#Current_codes)).

**Comment by blumk** [comment] 2018-03-10 14:16
@mledoze I think you can close this issue.

@enigma127 Feel free to reopen it, if you think the data set is incorrect.

**Closed** 2018-06-12 10:37 UTC
